create table if not exists public.handwriting_submissions (
 id bigint generated by default as identity primary key,
 submission_id uuid not null unique,
 participant_code text not null,
 started_at timestamptz not null,
 completed_at timestamptz not null,
 language text,
 sample_count integer not null default 0,
 payload jsonb not null,
 created_at timestamptz not null default now()
);
alter table public.handwriting_submissions enable row level security;
drop policy if exists "anonymous insert only" on public.handwriting_submissions;
create policy "anonymous insert only" on public.handwriting_submissions for insert to anon with check (sample_count > 0 and jsonb_typeof(payload)='object');
revoke all on table public.handwriting_submissions from anon;
grant insert on table public.handwriting_submissions to anon;
